server:
  port: 8082
  servlet:
    context-path: /order-service

spring:
  application:
    name: order-service

# Registration place
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
