server:
  port: 8083
  servlet:
    context-path: /employee-service

spring:
  application:
    name: employee-service

# Registration place
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
