server:
  port: 8081
  servlet:
    context-path: /product-service

spring:
  application:
    name: product-service

# Registration place
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
